# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
        
  publish:
        
    runs-on: ubuntu-latest

        
    steps:
        
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: devops159 
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Build the Docker image and push to Docker Hub
        working-directory: web-app
        
        env:
          IMAGE_TAG: ${{ github.sha }}

        run: |
          doker build . --file Docerfile --tag devops159/web_app_lab6:$IMAGE_TAG
          doker push devops159/web_app_lab6:$IMAGE_TAG